// دیکشنری کامل دسته‌بندی‌های ProductHunt به فارسی
export const CATEGORY_FA: Record<string, string> = {
  'Artificial Intelligence': 'هوش مصنوعی',
  'AI': 'هوش مصنوعی',
  'Machine Learning': 'یادگیری ماشین',
  'Developer Tools': 'ابزار توسعه‌دهندگان',
  'Productivity': 'بهره‌وری',
  'Design Tools': 'ابزار طراحی',
  'Design': 'طراحی',
  'SaaS': 'نرم‌افزار ابری',
  'Software': 'نرم‌افزار',
  'Web App': 'وب اپلیکیشن',
  'Mobile': 'موبایل',
  'iOS': 'آی‌او‌اس',
  'Android': 'اندروید',
  'Mac': 'مک',
  'Windows': 'ویندوز',
  'Linux': 'لینوکس',
  'Chrome Extensions': 'افزونه کروم',
  'Browsers': 'مرورگرها',
  'Finance': 'مالی',
  'Fintech': 'فین‌تک',
  'Banking': 'بانکداری',
  'Crypto': 'رمزارز',
  'Blockchain': 'بلاکچین',
  'Marketing': 'بازاریابی',
  'SEO': 'سئو',
  'Social Media': 'شبکه‌های اجتماعی',
  'Social': 'اجتماعی',
  'Communication': 'ارتباطات',
  'Messaging': 'پیام‌رسان',
  'Email': 'ایمیل',
  'Video': 'ویدیو',
  'Audio': 'صدا',
  'Music': 'موسیقی',
  'Podcasts': 'پادکست',
  'Photography': 'عکاسی',
  'Education': 'آموزش',
  'Learning': 'یادگیری',
  'Books': 'کتاب',
  'News': 'اخبار',
  'Media': 'رسانه',
  'Entertainment': 'سرگرمی',
  'Games': 'بازی',
  'Gaming': 'گیمینگ',
  'Health': 'سلامت',
  'Fitness': 'تناسب اندام',
  'Medical': 'پزشکی',
  'Mental Health': 'سلامت روان',
  'Wellness': 'بهزیستی',
  'Food': 'غذا',
  'Food & Drink': 'غذا و نوشیدنی',
  'Cooking': 'آشپزی',
  'Travel': 'سفر',
  'Transportation': 'حمل‌ونقل',
  'Automotive': 'خودرو',
  'Real Estate': 'املاک',
  'Home': 'خانه',
  'Parenting': 'فرزندپروری',
  'Kids': 'کودکان',
  'Pets': 'حیوانات خانگی',
  'Dating': 'دوستیابی',
  'Relationships': 'روابط',
  'Fashion': 'مد',
  'Beauty': 'زیبایی',
  'Shopping': 'خرید',
  'E-commerce': 'تجارت الکترونیک',
  'Retail': 'خرده‌فروشی',
  'Analytics': 'تحلیل داده',
  'Data': 'داده',
  'Business': 'کسب‌وکار',
  'Enterprise': 'سازمانی',
  'Startups': 'استارتاپ‌ها',
  'Entrepreneurship': 'کارآفرینی',
  'Hiring': 'استخدام',
  'HR': 'منابع انسانی',
  'Remote Work': 'کار از راه دور',
  'Team Collaboration': 'همکاری تیمی',
  'Project Management': 'مدیریت پروژه',
  'Task Management': 'مدیریت وظایف',
  'Notes': 'یادداشت',
  'Writing': 'نوشتن',
  'Publishing': 'انتشارات',
  'Newsletters': 'خبرنامه',
  'Blogging': 'وبلاگ‌نویسی',
  'Customer Support': 'پشتیبانی مشتری',
  'CRM': 'مدیریت ارتباط با مشتری',
  'Sales': 'فروش',
  'Legal': 'حقوقی',
  'Security': 'امنیت',
  'Privacy': 'حریم خصوصی',
  'APIs': 'رابط‌های برنامه‌نویسی',
  'Databases': 'پایگاه داده',
  'DevOps': 'دواپس',
  'Cloud': 'ابری',
  'Hosting': 'میزبانی',
  'Infrastructure': 'زیرساخت',
  'No-code': 'بدون کد',
  'Low-code': 'کم‌کد',
  'Open Source': 'متن‌باز',
  'GitHub': 'گیت‌هاب',
  'Code': 'کد',
  'Programming': 'برنامه‌نویسی',
  'General': 'عمومی',
  'Other': 'سایر',
  'Miscellaneous': 'متفرقه',
};

export function translateCategory(en: string): string {
  const trimmed = en.trim();
  return CATEGORY_FA[trimmed] ?? CATEGORY_FA[trimmed.replace(/\s+/g, ' ')] ?? trimmed;
}

export function translateCategories(joined: string): string {
  return joined
    .split('•')
    .map((c) => c.trim())
    .filter(Boolean)
    .map(translateCategory)
    .filter(Boolean)
    .join(' • ');
}
